/* eslint-disable import/prefer-default-export */
/*
 * @Author: zhangchenyang
 * @Date: 2022-04-20 10:52:56
 * @LastEditors: zhangchenyang
 * @LastEditTime: 2022-04-20 14:28:03
 */

// 快码
export enum LookupsCodeTypes {
  // 设备类型
  DEVICE_TYPE_CODE = 'TMIS.DEVICE.TYPE',
  // 楼层
  DEVICE_FLOOR = 'TMIS.DEVICE.FLOOR',
  // 设备状态
  DEVICE_PAGE_STATUS = 'TMIS.DEVICE.PAGE.STAUS',
  // 门店种类
  STROE_CATEGORY_CODE = 'TMIS.STORE.CATEGORYCODE',
  // 门店类型
  STROE_TYPE_CODE = 'TMIS.STORE.TYPE',
  // 广告发布状态
  AD_QUERY_APPROVE_CODE = 'TMIS.AD.QUERY.APPROVE.STATUS',
  // 是否支持特征广告
  SUPPORTEDFEATURE_CODE = 'TMIS.DEVICE.SUPPORTEDFEATURE',
  // 设备在线统计
  DEVICE_STATISTICS_CODE = 'TMIS.DEVICE.STATISTICS',
  // 设备广告播放利用率
  DEVICE_PLAY_RATE_CODE = 'TMIS.DEVICE.STATISTICS.AD_NOTICE',
  // 周期
  AD_CYCLE_TYPE_CODE = 'TMIS.AD.CYCLE.TYPE',
  // 广告等级类型
  AD_LEVEL_TYPE_CODE = 'TMIS.AD.LEVEL.TYPE',
  // 审批方式
  APPROVE_TYPE_CODE = 'TMIS.APPROVE.TYPE',
  // 操作类型
  OPERATION_TYPE_CODE = 'TMIS.NOTICE.OPERATION.TYPE',
  // 广告播放状态
  AD_PLAY_STATE_CODE = 'TMIS.AD.PLAY.STATE',
  // 通知播放状态
  NOTICE_STATUS_CODE = 'TMIS.NOTICE.STATUS',
  // 广告列表类型
  AD_TYPE_CODE = 'AD.QUERY.TYPE',
  // 分辨率快码
  DEVICE_RESOLUTION_TYPE = 'TMIS.DEVICE.RESOLUTION.TYPE',
  // 广告操作类型
  AD_OPERATE_STATE_CODE = 'TMIS.AD.OPERATE.STATE ',
  // 文本大小快码
  TEXT_SIZE_TYPE = 'TMIS.TEXT_SIZE',
  // 文本位置快码
  TEXT_POSITION_TYPE = 'TMIS.TEXT_POSITION',
  // 文本滚动速度快码
  NOTICE_ROLL_SPEED_TYPE = 'TMIS.NOTICE.SCROLL.SPEED',
  // 设备品牌业态
  DEVICE_BRAND_FORMAT = 'TMIS.DEVICE.BRAND_FORMAT',
  //缺省页设备状态
  DEVICE_TYPE_REPEAT = 'TMIS.DEVICE.TYPE.REPEAT',
  //审批设备状态
  APPROVE_STATUS_MANAGE = 'TMIS.APPROVE.STATUS.MANAGE',
  // 素材类型
  MATERIAL_SOURCE_TYPE = 'TMIS.MATERIAL.SOURCE.TYPE',
}
